### ISSUE TITLE
Add confetti script to Setup Wizard for completion step

### ISSUE THREAD

**Issue by unfulvio** [godaddy-wordpress/wc-plugin-framework#335]
While drafting an onboarding pitch for Social Login, I was thinking whether we want to add some small easter-eggish sprinkle to the Wizard. 

When a user completes the last step (and is successful) we could drop confetti using some reliable third party script.

For example: https://agezao.github.io/confetti-js/ (not that I'm suggesting to use this one specifically, but it portrays a few possibilities, including dropping custom SVG sprites).

Normally I don't like bloat, but this could have a very tiny footprint, and only discoverable when running the wizard til the end. If we have a custom effect dropping at the last screen, slightly different for each plugin (like the custom SVG above), then perhaps users, devs will want to see what we have added (this is the small easter egg bit).

There's a number of apps like Helpscout that does it, it doesn't bother me.

If we vote yay for this I could add a PR while working at a future setup wizard implementation.

If you like the idea of having some kind of easter egg at the end of the Setup Wizard that could encourage users running it, we could think of something else too.

**Comment by lkraav** [comment]
I was doing confetti research myself for gaming achievement congratulations screen, and it started to feel like a cannon / popper confetti effect would be more impactful.

https://codepen.io/johanmouchet/pen/qpjavE?page=3
