### ISSUE TITLE
WC function is_ajax is deprecated in WC 6.1

### ISSUE THREAD

**Issue by ianlin** [godaddy-wordpress/wc-plugin-framework#554]
Hello team!

I tried to create a PR but turned out I didn't have the permission to push a branch into this repo.

What I would like to add is replacing the WC function `is_ajax()` with the WP function `wp_doing_ajax()` as WooCommerce's `is_ajax()` function will be deprecated in WooCommerce `6.1`:

https://github.com/woocommerce/woocommerce/blob/71cdcf322c972d51fa6c767a445652e74f1a6e90/plugins/woocommerce/includes/wc-deprecated-functions.php#L1129-L1139

It suggests using a WP function `wp_doing_ajax()` instead which has been included in WordPress since 4.7: 

https://github.com/WordPress/WordPress/blob/e6b9b961305edd32fdfacc78eb6d93b22c3c8768/wp-includes/load.php#L1487-L1503

### Screenshots

<img width="2559" alt="Screenshot 2022-01-04 at 16 30 11" src="https://user-images.githubusercontent.com/914406/148030817-bb72c8fe-efa0-4541-8fd7-f7a6eefa016d.png">

**Comment by unfulvio-godaddy** [comment]
this has been addressed in https://github.com/godaddy-wordpress/wc-plugin-framework/releases/tag/5.10.12

thank you for the heads up and sorry for the late reply
