### ISSUE TITLE
Not possible to override credit card icons (or add new supported credit card type icon)

### ISSUE THREAD

**Issue by cadic** [godaddy-wordpress/wc-plugin-framework#561]
Looks like these lines of code expected to allow plugin developers add their custom credit card icons, within the plugin (first `if`), then using a fallback icon from the framework (second `if`)

https://github.com/skyverge/wc-plugin-framework/blob/0c79b5799955c59e644caf1da222c20c982eba06/woocommerce/payment-gateway/class-sv-wc-payment-gateway.php#L1755-L1763

But in fact, both ifs are equal and point to the same framework assets path. This makes impossible to add new supported credit card type or change the icons for existing types.

**Comment by unfulvio** [comment]
hey @cadic have replied to you in your PR in #562 -- thanks again for submitting your PR and many apologies for the late reply; the PR of yours will become part of #574 

I'm closing this now, but feel free to open issues in the future, we will be monitoring this repository more thoroughly moving forward
