### ISSUE TITLE
Return type of SV_WC_DateTime::getTimestamp()

### ISSUE THREAD

**Issue by dwdonline** [godaddy-wordpress/wc-plugin-framework#590]
wc-plugin-framework/woocommerce/compatibility/class-sv-wc-datetime.php:86

Return type of SV_WC_DateTime::getTimestamp() should either be compatible with DateTime::getTimestamp(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice.

This is a bug that anyone on php8+ experiences in gateways that use this framework. The solution which needs to be added to the code, is to change from:

`public function getTimestamp() {`

to

`public function getTimestamp():int {`

**Comment by unfulvio-godaddy** [comment]
Thank you for pointing this out @dwdonline ! We are aware of some changes needed for PHP 8.2. This seems something we can address in the FW. There should be additional warnings/deprecation notices for dynamically assigned properties (concerns gateways only) but for those we are waiting for a fix/workaround in WC: https://github.com/woocommerce/woocommerce/issues/31316

**Comment by unfulvio-godaddy** [comment]
Actually, turns out that class should be removed soon since it's been deprecated since v5.5.0. This may be something to go into upcoming version 5.11.0 which should also take care of HPOS: #584
