### ISSUE TITLE
Deprecated: Return type of SkyVerge\WooCommerce\PluginFramework\v5_10_12\SV_WC_DateTime::getTimestamp()

### ISSUE THREAD

**Issue by vorticy** [godaddy-wordpress/wc-plugin-framework#622]
With the debug log on, I get this warning several times quite often (like once every two seconds).

**Deprecated: Return type of SkyVerge\WooCommerce\PluginFramework\v5_10_12\SV_WC_DateTime::getTimestamp() should either be compatible with DateTime::getTimestamp(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /htdocs/web/app/plugins/woocommerce-avatax/vendor/skyverge/wc-plugin-framework/woocommerce/compatibility/class-sv-wc-datetime.php on line 85**

I contacted Avalara support and they said:  

During the review of this case and the error message provided, I was able to confirm that Avalara is not generating the error message referenced. 
Accordingly, we would not be able to determine the root cause of the issue. 
Additionally, during the review of this issue, I was able to locate some information that may help you resolve the issue or, at the least, help you on the way. Please consider that I was unable to verify the validity or the accuracy of the information below, so please dont consider the following information as a resolution. 
•	Please confirm the information with Skyverge
The deprecation notice you're encountering suggests that the return type of the getTimestamp() method in the SV_WC_DateTime class of the SkyVerge WooCommerce Plugin Framework is not compatible with the return type of the getTimestamp() method in the core DateTime class. To resolve this issue, you have a few options:
1.	Update the SkyVerge WooCommerce Plugin Framework: Check if there is an updated version of the SkyVerge WooCommerce Plugin Framework available. Upgrading to the latest version may include a fix for this deprecation notice.
2.	Modify the SV_WC_DateTime class: If you have the necessary expertise and access to the codebase, you can modify the SV_WC_DateTime class directly. To address the deprecation notice, you should ensure that the return type of the getTimestamp() method in SV_WC_DateTime is compatible with the return type of DateTime::getTimestamp(). You can achieve this by either changing the return type to int or applying the #[\ReturnTypeWillChange] attribute to temporarily suppress the notice. Here's an example of using the #[\ReturnTypeWillChange] attribute:
```
3.	phpCopy code
4.	class SV_WC_DateTime extends DateTime {
5.	    #[\ReturnTypeWillChange]
6.	    public function getTimestamp(): int {
7.	        // Method implementation
8.	    }
9.	}
```
10.	Note that this solution should only be used as a temporary measure until you can update to a version of the SkyVerge WooCommerce Plugin Framework that fully supports the required return type.
11.	Contact the plugin developer: If none of the above options work or you are not comfortable making changes to the codebase, it is recommended to reach out to the SkyVerge WooCommerce Plugin Framework developer or their support team. They should be able to provide guidance on how to resolve the deprecation notice and any necessary updates to the plugin.
Remember to always backup your code and database before making any modifications or updates to ensure that you can revert back in case any issues arise.
 
Thank you,
 
Ben Hoefer | Avalara Support
 
Avalara | Tax compliance done right

**Comment by vorticy** [comment]
Confused as to why this would be out of date?  Would the Woocommerce plugin update this framework during its own updates?   What is the best way to update the framework without messing anything up.  
WooCommerce version:	8.1.1
WordPress version:	6.3.1

**Comment by unfulvio-godaddy** [comment]
Hello Ben,

You are using a plugin that uses an older version of the Framework. The Framework must be updated by the plugin developer. The version 5.11.0 of the Framework fixes this issue. You may tell Avalara that they need update the FW in their plugin to 5.11.9 (latest) - this is the same as any PHP dependency and shouldn't be done by the user. The plugin needs a new release version.

I hope this addresses your question.

**Comment by vorticy** [comment]
> Hello there,
> 
> You are using a plugin that uses an older version of the Framework. The Framework is a PHP dependency, which must be manually updated by the plugin developer (Avalara) and included in a new release of the plugin. The version 5.11.0 of the Framework fixes the issue you are describing. You may tell Avalara that they need update the FW in their plugin to 5.11.9 (latest) - this is the same as any other PHP dependency and shouldn't be done by the user. The plugin needs a new release version, then you will see that update in among other WooCommerce plugin updates once it's released by the publisher (Avalara).
> 
> I hope this addresses your question.

Thank you much for straightening this out.  I will reach out to Avalara again and let them know.
