### ISSUE TITLE
Deprecated: Hook wcs_renewal_order_meta is <strong>deprecated</strong> since version wcs-core 2.5.0! Use wc_subscriptions_renewal_order_data instead.

### ISSUE THREAD

**Issue by lkraav** [godaddy-wordpress/wc-plugin-framework#640]
Heya. This has been spamming logs now for something like a couple of years. Could we get this refactored to the suggested meta key name? Tyvm!

Today's master

https://github.com/godaddy-wordpress/wc-plugin-framework/blob/346a347196b0d6df775f293d561a73f1ae096cd8/woocommerce/payment-gateway/integrations/class-sv-wc-payment-gateway-integration-subscriptions.php#L101

**Comment by unfulvio-godaddy** [comment]
hey @lkraav long time no chat! Thanks for pinging about this. Seems a small change that we could roll into #641 going out next week
