### ISSUE TITLE
Update Express Payment buttons to match incoming WooCommerce standard

### ISSUE THREAD

**Issue by peterwilsoncc** [godaddy-wordpress/wc-plugin-framework#655]
As documented in https://github.com/woocommerce/woocommerce-gateway-payfast/issues/183 and https://github.com/Automattic/woocommerce-payments/pull/6985, WooCommerce is in the process of updating the design requirements for the addition of Express Payment buttons.

On product pages:

* Express Pay buttons are to be moved below the add to cart button (currently above)
* -OR- separators are to be removed
* left/right margins removed to align buttons

On cart pages:

* Express Pay buttons are to be moved below the proceed to checkout button (currently above)
* -OR- separators are to be removed
* left/right margins removed to align buttons

For the cart pages, the buttons only need to be moved on the shortcode page. The block cart has sots for the placement of Express Pay buttons.

**Backward compatibility**

For third party extensions that combine adding buttons via their own code base and adding buttons via this framework, there will need to be a technique of managing backward compatibility to allow plugins to opt in to the new button placement.

This will avoid the situation in which a single extension adds some Express Payment options above the add/proceed buttons, and some Express Payment options below the add/proceed buttons.

This could either be achieved via a filter or a property and the relevant classes.

**Comment by unfulvio-godaddy** [comment]
hey @peterwilsoncc thanks for opening this issue

We are aware of the changes and we are in the process of adding support to Cart/Checkout blocks in our plugins starting from Payment Gateways. Release 5.12.0 shipped last week added support, but we haven't implemented support for "express" gateways such as Apple Pay or Google Pay.

Right now plugins that implement the FW need to implement block support for express checkout need to add their own JS code so maybe you could implement the changes in your own plugin while additional support is provided at FW level. If you have any relevant code that you'd like to submit as PR please be welcome to raise one.

I'll get back to this issue once we have made any relevant updates.

Thank you and happy holidays

Fulvio
