### ISSUE TITLE
Capture Charge bulk action option is being added to other list tables 

### ISSUE THREAD

**Issue by iamdharmesh** [godaddy-wordpress/wc-plugin-framework#724]
The **Capture Charge** bulk action option is added to other list tables when **HPOS** order storage is enabled. It is intended for capturing order payments and should only be displayed on the orders list table. However, it is currently appearing in the bulk action dropdowns of other list tables. For example: Plugins list table, Posts/Pages list table.

![image](https://github.com/user-attachments/assets/0d43c014-1bcc-4651-8f85-bc4f80b16d42)

Based on a quick check, it seems the `maybe_add_capture_charge_bulk_order_action()` method is hooked to admin_footer and doesn't have the appropriate checks to target only the orders list. As a result, it is applied to all list tables.
https://github.com/godaddy-wordpress/wc-plugin-framework/blob/fa2f5865ace430326677a309806c57ca6031c12a/woocommerce/payment-gateway/admin/class-sv-wc-payment-gateway-admin-order.php#L67

**Comment by unfulvio** [comment]
@agibson-godaddy It looks like there's a missing check in the callback to see if the current screen is `woocommerce_page_wc-orders` when the `admin_footer` is the `current_action()`: this should be an easy fix -- currently all gateways implementing the FW are affected

**Comment by agibson-godaddy** [comment]
Thank you for the info! Will aim to get this fixed for the next release.
